apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-lookup
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-lookup
    spec:
      init:
        command: [sh]
        args: [-c, 'helm dependency build && whoami && chmod -R 400 /.kube/config']
      generate:
        command: [ "sh", "-c" ]
        args: [ "helm template $ARGOCD_APP_NAME . -n $ARGOCD_APP_NAMESPACE --dry-run=server --validate --kubeconfig /.kube/config --kube-context kind-argohelm" ]